### ISSUE TITLE
ThemeProvider

### ISSUE THREAD

**Issue by ianwalter** [styled-components/vue-styled-components#26]
Thoughts on adding a ThemeProvider component that functions like the React version? I can try working on a PR this weekend if you'll accept this feature.

**Comment by liqueflies** [comment]
@ianwalter Any PR's is accepted, so if you want to working on it, I'll be glad and thankful :)

**Comment by ads1018** [comment]
Any progress on the ThemeProvider component?

**Comment by liqueflies** [comment]
hi @ads1018,
styled-components and vue-styled-components unluckily are two separated core.

styled-components involve the core and my work is to update my work too but it's impossible.
I'm trying to separate only the components of the framework (vue / react code) from the rest.

Than have the core repo and react / vue repo based con the core.
Now I'm very busy but I'm trying to do that, so I hope to have full-featured version of vue-styled-components :)

Hope it can sound good for you.

Thanks :)

**Comment by ads1018** [comment]
Cool thanks for the update!

**Comment by uriannrima** [comment]
Good night,

I've been loving using the framework. Since I've used this on React, couldn't hold myself not using something as styled-components on Vue. Then I found that some help was wanted to create a theme provider, and well, I created one using Provide/Inject, a bit of HOC (there is a Slot Scope version, but seems a bit verbose atm) and TSX. I had a bit of struggle since Typescript is a little annoying with some typings, but got it working... With reactiveness! The component is "transparent", so it will pass all of it's attributes and events, with a theme prop. I found the HOC option a bit better, since you can simple wrap the component.

Is still a work in progress. I'll test out to see if it doesn't have any "perfomance" issue, but I'll leave it here as a Gist. If @liqueflies allow, I'll create a PR, or maybe a separate package.

Here it go:
https://gist.github.com/uriannrima/1f0ab3bcb59943638dde014d49c3bcf3

Hope it helps. (:
