### ISSUE TITLE
Make component instances functional

### ISSUE THREAD

**Issue by Munter** [styled-components/vue-styled-components#34]
The current styled components instances are stateful, have methods and computeds. This has the unfortunate side effect of having styled components appear in [Vue devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) with no other information than that they have a class name.

Further more, if you return a styled component as your root node of your vue application, the entire application state is masked because the dev tools show the styled component instead of the application state.

It should be possible to convert the styled components to functional vue components and do the nessessary stylesheet calculations and injections in `render`  with a bit of closed over state keeping.

Benefits:
- Vue devtools improved debugging
- Lower memory footprint
- Possibility of improving the public API. Functional components pass on all props without a need to defined them in component props. Means dynamic style calculations could be done without defining prop types in styled component template interpolation

**Comment by mxstbr** [comment]
It's been a while since anything was changed here, I don't know what @1liqueflies is planning to do with this package, but I think a PR with these benefits would be very appreciated :blush:

**Comment by liqueflies** [comment]
Hi @Munter,
Unfortunately you can't make a styled-component functional, because I need computed and methods for style recalculation based on props, and functional component does not let you to access at `this`.
If you have any tips or ideas to make it functional, submit a PR or let me check some code :)

@mxstbr Unfortunately I was very busy in these months. My main goal still make a single repo with the official one (maybe with [lerna](https://github.com/lerna/lerna)?) and make only the `vue-part` from the styled-component logic, but it's impossible to do that alone and without planning the conditions / times / merge etc etc with the main repo.

We can open an issue also on main repo or use this for further discussions. :)

**Comment by Munter** [comment]
I had an idea of hooking into props in the functional components render function, manually check relevant prop updates and inject the recalculated stylesheet if needed. I would keep the state in a closure somewhere.

Obviously this is just a cursory idea that requires much more research and tests. I might send a PR, but I don't have any free time on my schedule for the next foreseeable future, so it might be a while

**Comment by liqueflies** [comment]
@Munter if you have any ideas please share with a PR.

**Comment by Munter** [comment]
Haven't had any time for a deep dive yet. Don't know when that will happen
