### ISSUE TITLE
Issue with select

### ISSUE THREAD

**Issue by minhchu** [styled-components/vue-styled-components#53]
Demo: https://codesandbox.io/s/ko0qrkwzj7

I have a styled `select` like this:
```
const SelectInput = styled.select`
  /* style here */
`;
```
and in my form component I use it like this:
```
      <SelectInput
        name="link"
        v-model="link"
        @change="onChangeHandler"
      >
        <option
          v-for="(option, index) in options"
          :value="option.value"
          :key="index"
          :selected="option.value === link ? 'selected' : ''"
        >
          {{ option.text }}
        </option>
      </SelectInput>
```
I would expect one option to be selected but it didn't:
![screenshot from 2018-08-24 12-20-16](https://user-images.githubusercontent.com/14136809/44566503-315f5900-a798-11e8-813b-8c0b5920deca.png)

I use just `select`( `<select v-model= ...>`) and it works fine:
![screenshot from 2018-08-24 12-20-38](https://user-images.githubusercontent.com/14136809/44566551-610e6100-a798-11e8-9aaf-789bcaaf869e.png)

Do you guys have any suggestions. Thanks in advance

**Comment by liqueflies** [comment]
Have you tried to use only the boolean value?

`:selected="option.value === link`

**Comment by minhchu** [comment]
@liqueflies I've tried but I haven't worked either :(

**Comment by minhchu** [comment]
I think the problem is hiding somewhere in these lines: https://github.com/styled-components/vue-styled-components/blob/master/src/models/StyledComponent.js#L22-L27

```
           on: {
              input: (event) => {
                this.$emit('input', event.target.value)
              },
              click: (event) => {
                this.$emit('click', event)
              }
            }
```

We only pass `input` and `click` events to children components but`select` needs `change` event :thinking:

**Comment by fsodano** [comment]
@minhchu I've been experiencing the same issue (working on a PR at the moment), but basically the problem is that `v-model` doesn't work.

My (custom) `Select` component currently works by doing:

```
                            <Select
                                    required
                                    v-bind:value="approved_by"
                                    v-on:select.native="approved_by = $event.target.value"
                            >
```

I've got the idea from this link: 
https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

And this question on StackOverflow: https://stackoverflow.com/questions/47311936/v-model-and-child-components

Hope it helps, but let me know if it doesn't as it's something I'm actively trying to solve. Cheers!

**Comment by minhchu** [comment]
I've just tried to add `change` event but it didnt work either

@fsodano nice ! Let me try. What is your PR id btw

**Comment by fsodano** [comment]
Cool, let me know @minhchu. There's no PR number at the moment as I haven't opened it yet, I've been struggling with the actual setup of the project so I just opened some PRs to fix that. I will update you once I have a solution working.

**Comment by minhchu** [comment]
@fsodano It doesn't work 

Let take a look at this sandbox: https://codesandbox.io/s/ko0qrkwzj7

**Comment by fsodano** [comment]
Hey @minhchu, I have noticed this issue as well. The error comes from these lines of `StyledComponent.js`:
 
```javascript
domProps: {
  value: this.value
}```

If you remove them, they work as expected.

Which is odd because @liqueflies has implemented it like Vue suggests here: https://vuejs.org/v2/guide/render-function.html#v-model

I am going to try to fix this issue this weekend, I'll post the PR# when I have one.

**Comment by minhchu** [comment]
Hey, it works great :+1: 

I check other libs and it seems that they don't implement `domProps`: https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/form-select/form-select.js

**Comment by liqueflies** [comment]
Hello,
#88 do the thing thanks a lot to @fsodano .

Thank you.
